name: Scheduled Sync
on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run sync
        run: python scripts/kiotviet_run_all.py
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          KIOTVIET_USERNAME: ${{ secrets.KIOTVIET_USERNAME }}
          KIOTVIET_PASSWORD: ${{ secrets.KIOTVIET_PASSWORD }}