name: KiotViet Data Sync (Test - Every 2 minutes)

on:
  schedule:
    # Test schedule: Run every 2 minutes for testing (remove after testing)
    - cron: '*/2 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome for Selenium
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        # Install ChromeDriver using a more reliable method
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Chrome version: $CHROME_VERSION"

        # Try to get ChromeDriver version that matches Chrome version
        CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chromedriver/downloads.html" | grep -oP "chromedriver \K\d+\.\d+\.\d+" | head -1)

        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          # Fallback to a known working version
          CHROMEDRIVER_VERSION="114.0.5735.90"
        fi

        echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"

        # Download ChromeDriver
        wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver

        # Verify installation
        chromedriver --version

    - name: Create data directory
      run: mkdir -p data/output

    - name: Run KiotViet sync
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
        KIOTVIET_USERNAME: ${{ secrets.KIOTVIET_USERNAME }}
        KIOTVIET_PASSWORD: ${{ secrets.KIOTVIET_PASSWORD }}
      run: |
        python scripts/kiotviet_run_all.py

    - name: Display results
      run: |
        echo "=== Sync Results ==="
        tail -20 cron.log || echo "No log file found"
        echo "=== Files Generated ==="
        ls -la data/output/ || echo "No output files"